#!/bin/bash

# To determine out where a process has been run from use ${PWD}
# echo "Script executed from: ${PWD}"
# 
# To figure out the directory of a file that's been executed run:
BASEDIR=$(dirname $0)
# echo "Script location: ${BASEDIR}"
# 
# Note: BASEDIR does not change when running a file within a file.


# Sends a notification banner to mac os
# 
# Takes 4 parameters
# message="What email would you like to use for your global git config?"
# title="Shell Install Script"
# subtitle="git"
# sound_name="Blow"    # optional
# 
# Sounds can be found in:
#    /System/Library/Sounds
#    ~/Library/Sounds
# 
# Ref:
#     https://apple.stackexchange.com/questions/57412/how-can-i-trigger-a-notification-center-notification-from-an-applescript-or-shel
function mac_notification_banner()
{

    message=$1
    title=$2
    subtitle=$3
    sound_name=$4
    if [ $sound_name ]; then
        use_sound="sound name \"$sound_name\""
    fi

    script="display notification \"$message\" with title \"$title\" subtitle \"$subtitle\"$use_sound"
    osascript -e "$script"
}


# Make a sound
# 
# Ref:
#   https://stackoverflow.com/questions/1143386/in-a-bash-script-command-how-can-i-make-a-pc-beep-noise-or-play-a-sound-file
function make_sound()
{
    echo -en "\007"
}

# Makes a sound, reads message then takes user inptu and returns it
# 
# Takes 1 parameters
# message="What email your email?"
function get_user_input(){
    message=$1

    make_sound
    echo $message
    read user_input
}