#!/bin/zsh
CONFIG_DIRECTORY="$(dirname $0)"
CONF_ZSHRC=$CONFIG_DIRECTORY/zshrc
# ln -s $CONF_ZSHRC ~/.zshrc


# to make file executeable run:
# chmod u+x <file_name>
# eg.
# chmod u+x install_scripts/fzf

# note: current config directory is passed to all script as arg ($1)
$CONFIG_DIRECTORY/install_scripts/homebrew $CONFIG_DIRECTORY
$CONFIG_DIRECTORY/install_scripts/git $CONFIG_DIRECTORY
$CONFIG_DIRECTORY/install_scripts/nvm $CONFIG_DIRECTORY
$CONFIG_DIRECTORY/install_scripts/fzf $CONFIG_DIRECTORY
$CONFIG_DIRECTORY/install_scripts/tmux $CONFIG_DIRECTORY
$CONFIG_DIRECTORY/install_scripts/vim $CONFIG_DIRECTORY
$CONFIG_DIRECTORY/install_scripts/pyenv $CONFIG_DIRECTORY
$CONFIG_DIRECTORY/install_scripts/node_globals $CONFIG_DIRECTORY
$CONFIG_DIRECTORY/install_scripts/zsh $CONFIG_DIRECTORY
