#!/bin/bash
source ../helpful_functions
echo "________________________________________
INSTALL SCRIPT: TMUX Start
"

TMUX=$HOME/.tmux.conf

# Set global tmux
function existing_tmux_conf(){
    if [ -e $TMUX ] ; then
        echo "INSTALL SCRIPT: $TMUX found, moving to $HOME/.tmux.conf.pre-install"

        mv  $TMUX $TMUX/.pre-install
    fi
}

if ! [ -L $TMUX ] ; then
    tmux_conf=$1/tmux.conf
    echo "INSTALL SCRIPT: .tmux.conf not symlinked $HOME. Creating softlink to $tmux_conf"
    echo $TMUX $tmux_conf
    ln -s $tmux_conf $TMUX
else
    echo "INSTALL SCRIPT: tmux config file already symlinked"
fi


if ! [ -d $HOME/.tmux-themepack ] ; then
    echo "INSTALL SCRIPT: .tmux-themepack not installed, cloning from github"
    
    git clone https://github.com/jimeh/tmux-themepack.git $HOME/.tmux-themepack
else
    echo "INSTALL SCRIPT: .tmux-themepack already installed"
fi


echo "
INSTALL SCRIPT: TMUX Finish
________________________________________"

