#!/bin/bash

echo "________________________________________
INSTALL SCRIPT: ZSH Start
"

if ! [ -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ] ; then
    echo "INSTALL SCRIPT:  ohmyzsh powerlevel10k not installed, cloning from github"
    
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
else
    echo "INSTALL SCRIPT: ohmyzsh powerlevel10k already installed"
fi

echo "
INSTALL SCRIPT: ZSH Finish
________________________________________"
